### PR TITLE
Fix segmentation fault for fragmented GRE packet

### PR DESCRIPTION
**Pull request by guidohu**
In case a fragmented IPv4 GRE packet was parsed it may led to a Segmentation fault. Because the second IPv4 packet did not contain a GRE header but the IP Protocol was still GRE.

### CODE REVIEW

**Comment by comotion** [comment]
nice catch. do you have a pcap to reproduce this?

**Comment by guidohu** [comment]
Hi Kacper

Please find the trouble-packet attached.

cheers
guido

2015-11-02 19:16 GMT+01:00 Kacper Why <notifications@github.com>:

**Comment by dbellavista** [comment]
Hi there! Why the hasn't the Pull Request imported yet? Have you found some bug or incompatibilities?

**Comment by gamelinux** [comment]
Just lack of time and testing. @dbellavista have you tried the patch? The patch seems OK to me. Merging.

**Pull request merged**
